apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata
  namespace: pdfdiff
spec:
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdfdiff-data
  namespace: pdfdiff
spec:
  storageClassName: local-path
