apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: pdfdiff
spec:
  template:
    spec:
      containers:
        - name: rabbitmq
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "700m"
              memory: "768Mi"
