apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: pdfdiff
spec:
  template:
    spec:
      containers:
        - name: worker
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
